ember-config {
  host = 0.0.0.0
  port = 8080
}

postgres-config {
  n-threads = 32
  url = "jdbc:postgresql:board"
  user = "docker"
  password = "docker"
}

security-config {
  secret = "secret"
  jwt-expiry-duration = "1 day"
}

email-service-config {
  host = "smtp.ethereal.email"
  port = 587
  user = "montana.bernier@ethereal.email"
  password = "p9EeJ56B5PnmSEb8yh"
  frontend-url = "https://google.com"
}

token-config {
  token-duration = 600000
}

stripe-config {
    price = "price_1SU1xYLbxgEJe3D88mzExgCk"
    key = "sk_test_51SU1nTLbxgEJe3D8Q0HtOrAhvcv2gPmWHqFM8fvPgckcWTEuG4aG8y8RUm2GSraPnPm9FKVLwiHOD1djI96ECalt00GzVMUo0P"
    success-url = "http://localhost:1234/jobs"
    cancel-url = "http://localhost:1234"
    webhook-secret = "whsec_8f13f5b31d2c72f28cbb2fccee069deaaddc36a0c15b36a3d6ed046ed771c879"
}