package com.jobaroo.ui.preset

import cats.syntax.semigroup.*
import com.jobaroo.ui.core.Css

object Daisy:

  object atoms:

    val btn               = Css.atom("btn")
    val btnPrimary        = Css.atom("btn-primary")
    val btnSecondary      = Css.atom("btn-secondary")
    val btnAccent         = Css.atom("btn-accent")
    val btnNeutral        = Css.atom("btn-neutral")
    val btnGhost          = Css.atom("btn-ghost")
    val btnOutline        = Css.atom("btn-outline")
    val btnSoft           = Css.atom("btn-soft")
    val btnActive         = Css.atom("btn-active")
    val btnSmall          = Css.atom("btn-sm")
    val btnLarge          = Css.atom("btn-lg")
    val btnBlock          = Css.atom("btn-block")
    val btnWide           = Css.atom("sm:btn-wide")
    val badge             = Css.atom("badge")
    val badgeLg           = Css.atom("badge-lg")
    val badgeNeutral      = Css.atom("badge-neutral")
    val badgePrimary      = Css.atom("badge-primary")
    val badgeSecondary    = Css.atom("badge-secondary")
    val badgeAccent       = Css.atom("badge-accent")
    val badgeOutline      = Css.atom("badge-outline")
    val card              = Css.atom("card")
    val cardBody          = Css.atom("card-body")
    val alert             = Css.atom("alert")
    val alertInfo         = Css.atom("alert-info")
    val alertSuccess      = Css.atom("alert-success")
    val alertWarning      = Css.atom("alert-warning")
    val alertError        = Css.atom("alert-error")
    val input             = Css.atom("input")
    val inputBordered     = Css.atom("input-bordered")
    val textarea          = Css.atom("textarea")
    val textareaBordered  = Css.atom("textarea-bordered")
    val select            = Css.atom("select")
    val selectBordered    = Css.atom("select-bordered")
    val checkbox          = Css.atom("checkbox")
    val checkboxPrimary   = Css.atom("checkbox-primary")
    val toggle            = Css.atom("toggle")
    val togglePrimary     = Css.atom("toggle-primary")
    val navbar            = Css.atom("navbar")
    val menu              = Css.atom("menu")
    val menuHorizontal    = Css.atom("menu-horizontal")
    val roundedBox        = Css.atom("rounded-box")
    val collapse          = Css.atom("collapse")
    val collapseArrow     = Css.atom("collapse-arrow")
    val collapseTitle     = Css.atom("collapse-title")
    val collapseContent   = Css.atom("collapse-content")
    val fieldset          = Css.atom("fieldset")
    val fieldsetLabel     = Css.atom("fieldset-label")
    val fileInput         = Css.atom("file-input")
    val fileInputBordered = Css.atom("file-input-bordered")
    val fileInputPrimary  = Css.atom("file-input-primary")
    val avatar            = Css.atom("avatar")
    val footer            = Css.atom("footer")
    val footerCenter      = Css.atom("footer-center")
    val hero              = Css.atom("hero")
    val heroContent       = Css.atom("hero-content")
    val link              = Css.atom("link")
    val linkHover         = Css.atom("link-hover")

  object groups:

    val buttonBase        = Css.of(atoms.btn)
    val badgeBase         = Css.of(atoms.badge, atoms.badgeLg)
    val cardBase          = Css.of(atoms.card)
    val cardBodyBase      = Css.of(atoms.cardBody)
    val alertBase         = Css.of(atoms.alert)
    val inputBase         = Css.of(atoms.input, atoms.inputBordered)
    val textareaBase      = Css.of(atoms.textarea, atoms.textareaBordered)
    val selectBase        = Css.of(atoms.select, atoms.selectBordered)
    val checkboxBase      = Css.of(atoms.checkbox, atoms.checkboxPrimary)
    val toggleBase        = Css.of(atoms.toggle, atoms.togglePrimary)
    val navbarBase        = Css.of(atoms.navbar)
    val menuBase          = Css.of(atoms.menu, atoms.menuHorizontal, atoms.roundedBox)
    val footerBase        = Css.of(atoms.footer, atoms.footerCenter)
    val heroBase          = Css.of(atoms.hero)
    val heroContentBase   = Css.of(atoms.heroContent)
    val collapseBase      = Css.of(atoms.collapse, atoms.collapseArrow)
    val fieldsetBase      = Css.of(atoms.fieldset)
    val fieldsetLabelBase = Css.of(atoms.fieldsetLabel)
    val fileInputBase     = Css.of(atoms.fileInput, atoms.fileInputBordered, atoms.fileInputPrimary)
    val linkBase          = Css.of(atoms.link, atoms.linkHover)

  object tone:

    val buttonPrimary   = Css.of(atoms.btnPrimary)
    val buttonSecondary = Css.of(atoms.btnSecondary)
    val buttonAccent    = Css.of(atoms.btnAccent)
    val buttonNeutral   = Css.of(atoms.btnNeutral)
    val buttonGhost     = Css.of(atoms.btnGhost)
    val buttonOutline   = Css.of(atoms.btnOutline)
    val buttonSoft      = Css.of(atoms.btnSoft)
    val badgeNeutral    = Css.of(atoms.badgeNeutral)
    val badgePrimary    = Css.of(atoms.badgePrimary)
    val badgeSecondary  = Css.of(atoms.badgeSecondary)
    val badgeAccent     = Css.of(atoms.badgeAccent)
    val badgeOutline    = Css.of(atoms.badgeOutline)
    val alertInfo       = Css.of(atoms.alertInfo)
    val alertSuccess    = Css.of(atoms.alertSuccess)
    val alertWarning    = Css.of(atoms.alertWarning)
    val alertError      = Css.of(atoms.alertError)

  object size:

    val buttonSmall = Css.of(atoms.btnSmall)
    val buttonLarge = Css.of(atoms.btnLarge)
    val buttonFull  = Css.of(atoms.btnBlock, atoms.btnWide)
